### ISSUE TITLE
Alpha Epic

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulp-docs#1]
Implementation for minimal usage.

## Basic features:
- [x] **Aggregation**: aggregate content from repositories in the desired main-schema.
- [x] **Reference Build**: figure out how to build each repository Reference section, or if that will be pre-build individually.
- [x] **REST Api Build**: building the restapi docs is not trivial, so I added a workaround (link to existing pages).
- [x] **pulp-docs serve**: run `mkdocs serve` with the `mkdocs.yml` shipped with pulp-docs package
- [x] **GitHub Downloader**: downloader to get the latests release codebase from a repo. (currently mocking w/ local copies)
- [x] **pulp-docs build**: run `mkdocs build` with repositories downloaded from latest github release
- [x] **Inter-repo links**: check this works properly
- [x] **Flexbile Configuration**: currently, the fixture repos are hardcoded
