### ISSUE TITLE
[EPIC] Unified Documentation Part 2

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulp-docs#30]
The goal of this EPIC is to make the [new Pulp Docs](https://staging-docs.pulpproject.org/) site production-ready and publish it under https://pulpproject.org/.

Community Post: https://discourse.pulpproject.org/t/unified-documentation-part-2/1188
Previous Epic: https://github.com/pulp/pulpcore/issues/5037

## First Step

- [x] [CI] #31
- [x] [misc] #33 
- [x] [misc] #32 (rst repos)

## Second Step

- [x] [pulp-docs] #20 
- [x] [pulp-docs] #9 
- [x] [pulp-docs] https://github.com/pulp/pulp-docs/issues/40

## Last Step

- [x] [publish] Publish promote staging-docs.pulpproject to pulpproject.org
- [x] [publish] Add redirects to pulpproject.org

## Nice to Have

- [publish] Use latest released versions of each repository instead of main
- [content] General Review: fix internal links, image links, and general rendering issues (all repos)
- [pulp-docs] Improve Repository Map table (e.g, w/ correct versions)
- [pulp-docs] Add toc-summary on plugins index page (to get quicker overview of all content)
- [content] Main "getting started" tutorial
- [content] Installation docs in oci-images
- [content] Merge content from pulpproject.org into docs
- [pulp-docs] #34
- [CI] https://github.com/pulp/pulpcore/issues/5085 (nice-to-have)

**Comment by pedro-psb** [comment]
Core task are done.
Nice-to-haves will be done as demanded
